# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: kanbanboard-dev Build and Deploy

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install and build React app
        run: |
          cd kanban-react-vite-app
          npm install
          npm run build

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4 
        with:
          dotnet-version: '8.x'
          include-prerelease: true

      - name: Build with dotnet
        run: |
              dotnet restore
              dotnet build --configuration Release
        working-directory: Kanban.Server.WebApp
        
      - name: Run Unit tests
        run: |
              dotnet restore
              dotnet test --configuration Release
        working-directory: Kanban.Server.Domain.UnitTests
        
      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp
        working-directory: Kanban.Server.WebApp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'kanbanboard-dev'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_DEV }}
          package: .
